compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
      source:
            ghcjs-0.2.0.20151029_ghc-7.10.2:
                    url: "https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz"
resolver: lts-3.13
packages:
- '.'
- location:
    git: git@github.com:ryantrinkle/reflex-dom.git
    commit: f4dbdd799260bc203f7f5cdce18362cb896f6d57
  extra-dep: true
extra-deps:
- repline-0.1.4.0
- pretty-tree-0.1.0.0
- ghcjs-dom-0.2.3.1
- ref-tf-0.4
- reflex-0.3.2
- these-0.6.1.0
flags: {}
extra-package-dbs: []
